### ISSUE TITLE
No License?

### ISSUE THREAD

**Issue by chorman0773** [ShootMe/LiveSplit.DeSmuME#1]
I was searching for something that could be used to write an autosplitter and IGT reader for Fossil Fighters Champions, and I found this. However I noticed that there is no license on the repo? This may have been intentional, but is usually done in error:
See -> https://choosealicense.com/

**Comment by ShootMe** [comment]
Yea, I usually don't care to put licenses in the repos themselves. All my livesplit stuff is MIT.

**Comment by chorman0773** [comment]
Cool thanks. I’m probably going to write in an Game Clock Reader so it can also do IGT then pr it.
